---
title:
- type: main
  text: Labour's New Economics
creator:
- role: author
  text: Grace Blakeley
- role: author
  text: Tom Gann
- role: author
  text: Joe Guinan
- role: author
  text: Dan Hind
- role: author
  text: Wendy Liu
- role: author
  text: Thomas M. Hanna
- role: author
  text: Chris MacMackin
- role: author
  text: Andrea Marie
- role: author
  text: John Marlow
- role: author
  text: John McDonnell MP
- role: author
  text: Tom Mills
- role: author
  text: Nic Murray
- role: author
  text: Tom O'Shea
- role: author
  text: David Quentin
- role: author
  text: Justin Reynolds
publisher: New Socialist
rights: "© 2018 New Socialist"
lang: en-GB
date: 8 July 2018
cover-image: "/Users/joe/Projects/nsbooks/labours-new-economics/cover-A5.png"
...